# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boissons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consommateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='consommation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boissons.boissons')),
                ('consommateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommateurs.consommateurs')),
            ],
        ),
    ]
